version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "5555:5555"
    volumes:
      - ./server:/app
    network_mode: bridge

  client:
    build:
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app
    network_mode: bridge
    stdin_open: true
    tty: true
